---
- name: Ensure that directories is exists
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
  - /etc/profile.d
  - /etc/systemd/system/docker.service.d
  - /opt/bin  
