---
mesos_version: 0.22.1
mesos_cluster_name: mesos
mesos_work_dir: /mnt/mesos/data
mesos_log_dir: /mnt/mesos/log
mesos_master_group: mesos_masters
mesos_slave_group: mesos_slaves
zookeeper_server_group: zookeeper_nodes

mesos_master_node_index: "
    {%- for host in groups[mesos_master_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}"
mesos_slave_node_index: "
    {%- for host in groups[mesos_slave_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}"
       
mesos_master_name: "{{ mesos_master_node_index }}.master.mesos"
mesos_master_cidr: "10.128.3.{{ mesos_master_node_index }}/16"
mesos_slave_name: "{{ mesos_slave_node_index }}.slave.mesos"
mesos_slave_cidr: "10.128.4.{{ mesos_slave_node_index }}/16"

mesos_zookeeper_nodes: "
  {%- set zookeeper_peers = [] -%}
  {%- for host in groups[zookeeper_server_group] -%}
    {% do zookeeper_peers.append('10.128.2.%s:2181' % loop.index) %}
  {%- endfor -%}
  {{ zookeeper_peers | join(',') }}"
mesos_quorum: 1
