---
- name: Upload /etc/consul.env template
  sudo: yes
  template:
    src: consul.env.j2
    dest: "/etc/consul.env"
    mode: 0600
  register: consul_env

- name: Copy consul.service
  sudo: yes
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service
  register: consul_service
  
- name: Reload SystemD
  sudo: yes
  command: systemctl daemon-reload
  when: consul_service.changed

- name: Restart Consul Agent
  sudo: yes
  service:
    enabled: yes
    name: consul
    state: restarted
  when: consul_service.changed or consul_env.changed