---
- name: Copy mesos-master.service
  sudo: yes
  copy:
    src: mesos-master.service
    dest: /etc/systemd/system/mesos-master.service
  register: mesos_master_service
  when: mesos_master_mode
  notify:
  - Reload SystemD
  - Restart Mesos Master
  
- name: Copy mesos-slave.service
  sudo: yes
  copy:
    src: mesos-slave.service
    dest: /etc/systemd/system/mesos-slave.service
  register: mesos_slave_service
  when: not mesos_master_mode
  notify:
  - Reload SystemD
  - Restart Mesos Slave
  
- name: Upload /etc/mesos_master.env template
  sudo: yes
  template:
    src: mesos_master.env.j2
    dest: /etc/mesos_master.env
    mode: 0600
  register: mesos_master_env
  when: mesos_master_mode
  notify:
  - Restart Mesos Master
  
- name: Upload /etc/mesos_slave.env template
  sudo: yes
  template:
    src: mesos_slave.env.j2
    dest: /etc/mesos_slave.env
    mode: 0600
  register: mesos_slave_env
  when: not mesos_master_mode
  notify:
  - Restart Mesos Slave
  
- name: Ensure that work_dir exists
  sudo: yes
  file:
    path: "{{ mesos_work_dir }}"
    state: directory
    mode: 0755
  notify:
  - Restart Mesos Master
  - Restart Mesos Slave
  
- name: Ensure that log_dir exists
  sudo: yes
  file:
    path: "{{ mesos_log_dir }}"
    state: directory
    mode: 0755
  notify:
  - Restart Mesos Master
  - Restart Mesos Slave
    
- name: Docker pull image
  command: "/usr/bin/docker pull cleawing/mesos:{{ mesos_version }}"
  when: mesos_master_service.changed or mesos_slave_service.changed or mesos_master_env.changed or mesos_slave_env.changed
  register: mesos_image_pulled
  until: mesos_image_pulled.changed
