---
weave_docker_subnet: "10.2.{{ weave_node_index }}.0/24"

weave_launch_peers: "
  {%- set weave_peers = [] -%}
  {%- for host in groups[weave_group] -%}
    {%- if host != inventory_hostname and host not in weave_peers -%}
      {% do weave_peers.append(hostvars[host]['ansible_eth1']['ipv4']['address']) %}
    {%- endif -%}
  {%- endfor -%}
  {{ weave_peers|join(' ') }}"

weave_docker_opts: "--bridge=weave --fixed-cidr={{ weave_docker_subnet }} --icc=false"