---
- name: Copy 10-weave.network
  copy:
    src: 10-weave.network
    dest: /etc/systemd/network/10-weave.network
  notify:
  - Restart Network
  
- name: Copy weave-network.target
  copy:
    src: weave-network.target
    dest: /etc/systemd/system/weave-network.target
  register: weave_network_target
  notify:
  - Reload SystemD
        
- name: Copy install-weave.service
  copy:
    src: install-weave.service
    dest: /etc/systemd/system/install-weave.service
  register: install_weave_service
  notify:
  - Reload SystemD
  
- name: Copy weave.service
  copy:
    src: weave.service
    dest: /etc/systemd/system/weave.service
  register: weave_service
  notify:
  - Reload SystemD
    
- name: Upload /etc/weave.env template
  template:
    src: weave.env.j2
    dest: "/etc/weave.env"
    mode: 0600
  register: weave_env
  
- meta: flush_handlers

- name: Pull Docker Images
  command: docker pull {{ item }}
  with_items:
    - weaveworks/weave:latest
    - weaveworks/weavedns:latest
    - weaveworks/weaveexec:latest
  when: install_weave_service.changed
  register: weave_pulled
  until: weave_pulled.changed
    
- name: Install Weave
  service:
    enabled: yes
    name: install-weave
    state: restarted
  when: install_weave_service.changed and weave_pulled.changed
  register: weave_installed
    
- name: Assign IP to weave bridge
  command: "ip addr add dev weave {{ weave_bridge_ip }}"
  when: weave_installed.changed
  ignore_errors: True
  
- name: Adjust /etc/default/docker
  lineinfile:
    dest: /etc/default/docker
    line: 'DOCKER_NETWORK="{{ weave_docker_opts }}"'
  when: weave_installed.changed
  notify:
  - Restart Docker
  
- meta: flush_handlers
      
- name: Restart Weave Router
  service:
    enabled: yes
    name: weave
    state: restarted
  when: install_weave_service.changed or weave_service.changed or weave_env.changed
  notify:
  - Waiting for Weave Router