---
- name: Copy 10-weave.network
  sudo: yes
  copy:
    src: 10-weave.network
    dest: /etc/systemd/network/10-weave.network
  notify:
  - Restart Network
  
- name: Copy weave-network.target
  sudo: yes
  copy:
    src: weave-network.target
    dest: /etc/systemd/system/weave-network.target
  register: weave_network_target
  notify:
  - Reload SystemD
  
- name: Assure /etc/systemd/system/docker.service.d exists
  sudo: yes
  file: path=/etc/systemd/system/docker.service.d state=directory
      
- name: Adjust Docker
  sudo: yes
  copy:
    src: 10-docker-adjust.conf
    dest: /etc/systemd/system/docker.service.d/10-docker-adjust.conf
  register: docker_adjust
  notify:
  - Reload SystemD
  - Restart Docker
      
- name: Copy install-weave.service
  sudo: yes
  copy:
    src: install-weave.service
    dest: /etc/systemd/system/install-weave.service
  register: install_weave_service
  notify:
  - Reload SystemD
  
- name: Copy weave.service
  sudo: yes
  copy:
    src: weave.service
    dest: /etc/systemd/system/weave.service
  register: weave_service
  notify:
  - Reload SystemD
  
- name: Copy weave-dns.service
  sudo: yes
  copy:
    src: weave-dns.service
    dest: /etc/systemd/system/weave-dns.service
  register: weave_dns
  notify:
  - Reload SystemD

- name: Copy weave-proxy.service
  sudo: yes
  copy:
    src: weave-proxy.service
    dest: /etc/systemd/system/weave-proxy.service
  register: weave_proxy
  notify:
  - Reload SystemD
  
- name: Upload /etc/weave.env template
  sudo: yes
  template:
    src: weave.env.j2
    dest: "/etc/weave.env"
    mode: 0600
  register: weave_env
  
- meta: flush_handlers
  
- name: Install Weave
  sudo: yes
  service:
    enabled: yes
    name: install-weave
    state: restarted
  when: install_weave_service.changed
          
- name: Restart Weave Router
  sudo: yes
  service:
    enabled: yes
    name: weave
    state: restarted
  when: install_weave_service.changed or weave_service.changed or weave_env.changed
  notify:
  - Waiting for Weave Router

# TODO. wait_for for UDP ports (and wait for Weave DNS)
- name: Restart Weave DNS
  sudo: yes
  service:
    enabled: yes
    name: weave-dns
    state: restarted
  when: install_weave_service.changed or weave_service.changed or weave_env.changed or weave_dns.changed
  ignore_errors: True

- name: Restart Weave Proxy
  sudo: yes
  service:
    enabled: yes
    name: weave-proxy
    state: restarted
  when: install_weave_service.changed or weave_service.changed or weave_env.changed or weave_proxy.changed
  ignore_errors: True
  notify:
  - Waiting for Weave Proxy
  