---
- name: Copy 10-weave.network
  copy:
    src: 10-weave.network
    dest: /etc/systemd/network/10-weave.network
  notify:
  - Restart Network
  
- name: Copy weave-network.target
  copy:
    src: weave-network.target
    dest: /etc/systemd/system/weave-network.target
  register: weave_network_target
  notify:
  - Reload SystemD
  
- name: Upload weave templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: 0600
  with_items:
  - weave.env
  - weave-nginx.env
  - weave-nginx.conf
  register: weave_templates
  
- name: Copy Weave services
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
  - weave.service
  - weave-dns.service
  - weave-proxy.service
  - weave-proxy-nginx.service
  register: weave_services
  notify:
  - Reload SystemD
    
- name: Adjust DOCKER_NETWORK
  lineinfile:
    dest: /etc/default/docker
    line: 'DOCKER_NETWORK="{{ weave_docker_opts}}"'
  notify:
  - Restart Docker
  
- meta: flush_handlers

- name: Restart Weave Services
  service:
    enabled: yes
    name: "{{ item }}"
    state: restarted
  with_items:
  - weave
  - weave-dns
  - weave-proxy
  - weave-proxy-nginx
  when: weave_services.changed or weave_templates.changed
  notify:
  - Waiting for Weave Router
  - Waiting for Weave Proxy
  
- name: Adjust ~/.profile
  sudo: no
  lineinfile:  
    dest: "~/.profile"
    line: "export DOCKER_HOST='unix://{{ weave_unix_socket }}'"
    
- meta: flush_handlers