---
- name: Copy 10-weave.network
  sudo: yes
  copy:
    src: 10-weave.network
    dest: /etc/systemd/network/10-weave.network
  notify:
  - Restart Network
  
- name: Copy weave-network.target
  sudo: yes
  copy:
    src: weave-network.target
    dest: /etc/systemd/system/weave-network.target
  register: weave_network_target
  notify:
  - Reload SystemD
  
- name: Upload weave templates
  sudo: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: 0600
  with_items:
  - weave.env
  - weave-nginx.env
  - weave-nginx.conf
  register: weave_templates
  
- name: Copy Weave services
  sudo: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
  - weave.service
  - weave-dns.service
  - weave-proxy.service
  - weave-proxy-nginx.service
  register: weave_services
  notify:
  - Reload SystemD
  
- name: Adjust DOCKER_OPTS
  sudo: yes
  template:
    src: 10-weave.conf.j2
    dest: /etc/systemd/system/docker.service.d/10-weave.conf
    mode: 0600
  notify:
  - Restart Docker
  
- meta: flush_handlers

- name: Enable Weave Services
  sudo: yes
  service:
    enabled: yes
    name: "{{ item }}"
  with_items:
  - weave-network.target
  - weave
  - weave-dns
  - weave-proxy
  - weave-proxy-nginx

- name: Restart Weave Services
  sudo: yes
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - weave-network.target
  - weave
  - weave-dns
  - weave-proxy
  - weave-proxy-nginx
  when: weave_services.changed or weave_templates.changed
  notify:
  - Waiting for Weave Router
  - Waiting for Weave Proxy

- name: Touch /etc/profile.d/docker_host.sh
  sudo: yes
  file: 
    path: /etc/profile.d/docker_host.sh
    state: touch
  
- name: Adjust /etc/profile.d/docker_host.sh
  sudo: yes
  lineinfile:  
    dest: /etc/profile.d/docker_host.sh
    line: "export DOCKER_HOST='unix://{{ weave_unix_socket }}'"
    
- meta: flush_handlers