---
- name: Check that OpenVSwitch installed and extract version
  shell: "ovs-vsctl -V"
  ignore_errors: True
  register: ovs_installed
  
- name: Install packages
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - bridge-utils 
    - openvswitch-switch
    - openvswitch-ipsec
    - openvswitch-vtep
    - openvswitch-pki
  when: ovs_installed | failed
  register: ovs_pkg_installed
  until: ovs_pkg_installed.changed
  
- name: Enable Racoon service
  service:
    enabled: yes
    name: racoon
    state: started
    
- name: Upload /etc/network/interfaces.d/ovs-network.cfg template
  template:
    src: ovs-network.cfg.j2
    dest: /etc/network/interfaces.d/ovs-network.cfg
    
- name: Restart Networking
  service:
    name: networking
    state: restarted
    
- name: Set VLAN for br0
  command: ovs-vsctl set port br0 tag=100
    