---
- name: Check that OpenVSwitch installed and extract version
  shell: "ovs-vsctl -V"
  ignore_errors: True
  register: ovs_installed
  
- name: Install packages
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
    install_recommends: no
  with_items:
    - bridge-utils 
    - openvswitch-switch
    - openvswitch-ipsec
    - openvswitch-vtep
    - openvswitch-pki
  when: ovs_installed | failed
  register: ovs_pkg_installed
  until: ovs_pkg_installed.changed
  
- name: Enable Racoon service
  service:
    enabled: yes
    name: racoon
    state: started
  when: ovs_pkg_installed.changed
    
    