---
- name: Copy 10-weave.network
  sudo: yes
  copy: src=10-weave.network dest=/etc/systemd/network/10-weave.network
  notify:
  - Restart Network

- name: Assure /etc/systemd/system/docker.service.d exists
  sudo: yes
  file: path=/etc/systemd/system/docker.service.d state=directory
  
- name: Drop-in 10-docker-disable-icc.conf
  sudo: yes
  copy: src=10-docker-disable-icc.conf dest=/etc/systemd/system/docker.service.d/10-docker-disable-icc.conf
  notify:
  - Restart Docker
    
- name: Copy install-weave.service
  sudo: yes
  copy: src=install-weave.service dest=/etc/systemd/system/install-weave.service
  notify:
  - Reload SystemD
  
- name: Copy weave.service
  sudo: yes
  copy: src=weave.service dest=/etc/systemd/system/weave.service
  notify:
  - Reload SystemD
  - Restart Weave
          
- name: Upload /etc/weave.env template
  sudo: yes
  template:
    src: weave.env.j2
    dest: "/etc/weave.env"
    mode: 0600
  notify:
  - Restart Weave