---
- name: Copy 10-weave.network
  sudo: yes
  copy:
    src: 10-weave.network
    dest: /etc/systemd/network/10-weave.network
  register: weave_network

- name: Restart Network
  sudo: yes
  service:
    name: systemd-networkd
    state: restarted
  when: weave_network.changed
  
- name: Copy weave-network.target
  sudo: yes
  copy:
    src: weave-network.target
    dest: /etc/systemd/system/weave-network.target
  register: weave_network_target
      
- name: Copy install-weave.service
  sudo: yes
  copy:
    src: install-weave.service
    dest: /etc/systemd/system/install-weave.service
  register: install_weave_service
  
- name: Copy weave.service
  sudo: yes
  copy:
    src: weave.service
    dest: /etc/systemd/system/weave.service
  register: weave_service

- name: Upload /etc/weave.env template
  sudo: yes
  template:
    src: weave.env.j2
    dest: "/etc/weave.env"
    mode: 0600
  register: weave_env

- name: Upload /etc/docker.env template
  sudo: yes
  template:
    src: docker.env.j2
    dest: "/etc/docker.env"
    mode: 0600
  register: docker_env
  
- name: Reload SystemD
  sudo: yes
  command: systemctl daemon-reload
  when: weave_network_target.changed or install_weave_service.changed or weave_service.changed

- name: Install Weave
  sudo: yes
  service:
    enabled: yes
    name: install-weave
    state: started
  when: install_weave_service | changed
  
- name: Check Weave bridge exists
  raw: stat /sys/class/net/weave
  register: need_weave_bridge
  ignore_errors: True
  
- name: Create Weave bridge
  sudo: yes
  command: /opt/bin/weave create-bridge
  when: need_weave_bridge | failed
          
- name: Assure /etc/systemd/system/docker.service.d exists
  sudo: yes
  file: path=/etc/systemd/system/docker.service.d state=directory
      
- name: Inject Weave bridge into Docker
  sudo: yes
  template:
    src: 10-docker-weave-bridge.conf.j2
    dest: /etc/systemd/system/docker.service.d/10-docker-weave-bridge.conf
  register: docker_weave_bridge_conf

- name: Reload SystemD
  sudo: yes
  command: systemctl daemon-reload
  when: docker_weave_bridge_conf.changed
      
- name: Restart Docker
  sudo: yes
  service:
    name: docker
    state: restarted
  when: docker_env.changed or docker_weave_bridge_conf.changed
  
- name: Restart Weave
  sudo: yes
  service:
    enabled: yes
    name: weave
    state: restarted
  when: install_weave_service.changed or weave_env.changed or weave_service.changed