---
- name: Restart Network
  service:
    name: systemd-networkd
    state: restarted
    
- name: Restart Networking
  service:
    name: networking
    state: restarted

- name: Reload SystemD
  command: systemctl daemon-reload

- name: Restart Docker
  service:
    enabled: yes
    name: docker
    state: restarted