---
consul_version: 0.5.2
consul_data: /mnt/consul/data
consul_master_group: consul_masters
consul_slave_group: consul_slaves

consul_master_node_index: "
    {%- for host in groups[consul_master_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
"
consul_slave_node_index: "
    {%- for host in groups[consul_slave_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
"
consul_master_host_name: "{{ consul_master_node_index }}.master.consul"
consul_slave_host_name: "{{ consul_slave_node_index }}.slave.consul"

consul_retry_join: " 
  {{ master_join_peers.split(',') | join(' -retry-join ') }}"
  
consul_master_args: "-server -bootstrap-expect {{ groups[consul_master_group] | length }}"
consul_bridge_ip: "{{ weave_bridge_ip | replace('/16', '') }}"