---
zookeeper_version: 3.4.6
zookeeper_data: /mnt/zookeeper
zookeeper_server_group: zookeeper_nodes
zookeeper_node_index: "
    {%- for host in groups[zookeeper_server_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
"
zookeeper_name: "{{ zookeeper_node_index }}.zookeeper"
zookeeper_cidr: "10.127.2.{{ consul_master_node_index }}/16"

zookeeper_nodes_env: "
  {%- set zookeeper_peers = [] -%}
  {%- for host in groups[zookeeper_server_group] -%}
    {% do zookeeper_peers.append('ADDITIONAL_ZOOKEEPER_%s=server.%s=10.127.2.%s:2888:3888' % (loop.index, loop.index, loop.index)) %}
  {%- endfor -%}
  {{ zookeeper_peers | join(' -e ') }}"
zookeeper_docker_args: "-e SERVER_ID={{ zookeeper_node_index }} -e {{ zookeeper_nodes_env }}"
