- hosts: all
  gather_facts: False
  roles:
    - coreos-bootstrap
    
- hosts: all
  roles:
#    - common
#    - docker-install
    - docker-common
    - weave-install
    - weave-networking

- hosts: masters
  roles:
    - { role: consul, consul_master_mode: true }
    - zookeeper
    - { role: mesos, mesos_master_mode: true }
    - mesos-marathon
    
- hosts: slaves
  roles:
    - { role: consul, consul_master_mode: false }
    - { role: mesos, mesos_master_mode: false }