- hosts: all
  roles:
    - common
    - docker
    - weave

#- hosts: masters
#  roles:
#    - { role: consul, consul_master_mode: true }
#    - zookeeper
#    - { role: mesos, mesos_master_mode: true }
    
#- hosts: slaves
#  roles:
#    - { role: consul, consul_master_mode: false }
#    - { role: mesos, mesos_master_mode: false }