---
- name: Copy zookeeper.service
  sudo: yes
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service
  register: zookeeper_service
  notify:
  - Reload SystemD
  - Restart Zookeper Node
  
- name: Upload /etc/zookeeper.env template
  sudo: yes
  template:
    src: zookeeper.env.j2
    dest: /etc/zookeeper.env
    mode: 0600
  register: zookeeper_env
  notify:
  - Restart Zookeper Node
  
- name: Ensure that data path exists
  sudo: yes
  file:
    path: "{{ zookeeper_data }}"
    state: directory
    mode: 0755
  notify:
  - Restart Zookeper Node
  
- name: Docker pull image
  command: "/usr/bin/docker pull cleawing/zookeeper:{{ zookeeper_version }}"
