---
- name: Copy consul-master.service
  sudo: yes
  copy:
    src: consul-master.service
    dest: /etc/systemd/system/consul-master.service
  when: consul_master_mode
  register: consul_master_service
  notify:
  - Reload SystemD
  - Restart Consul Master
  
- name: Copy consul-slave.service
  sudo: yes
  copy:
    src: consul-slave.service
    dest: /etc/systemd/system/consul-slave.service
  when: not consul_master_mode
  register: consul_slave_service
  notify:
  - Reload SystemD
  - Restart Consul Slave
  
- name: Upload /etc/consul_master.env template
  sudo: yes
  template:
    src: consul_master.env.j2
    dest: "/etc/consul_master.env"
    mode: 0600
  register: consul_master_env
  when: consul_master_mode 
  notify:
  - Restart Consul Master
  
- name: Upload /etc/consul_slave.env template
  sudo: yes
  template:
    src: consul_slave.env.j2
    dest: "/etc/consul_slave.env"
    mode: 0600
  register: consul_slave_env
  when: not consul_master_mode 
  notify:
  - Restart Consul Slave

- name: Ensure that data path exists
  sudo: yes
  file:
    path: "{{ consul_data }}"
    state: directory
    mode: 0755
  notify:
  - Restart Consul Master
  - Restart Consul Slave
  
- name: Docker pull image
  command: "/usr/bin/docker pull cleawing/consul:{{ consul_version }}"
  when: consul_master_env.changed or consul_slave_env.changed or consul_master_service.changed or consul_slave_service.changed
  register: consul_image_pulled
  until: consul_image_pulled.changed