---
- name: Update Weave script
  sudo: yes
  get_url:
    url: http://git.io/weave
    dest: /opt/bin/weave
    mode: 0755
  register: weave_updated
  until: weave_updated | success
  
- name: Setup Weave
  command: /opt/bin/weave setup
  when: weave_updated | changed
  register: weave_installed 
  until: weave_installed | success